### ISSUE TITLE
LSP only updates when opening file

### ISSUE THREAD

**Issue by Jummit** [mfussenegger/nvim-jdtls#245]
### LSP client configuration

```lua
local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
require"jdtls".start_or_attach{
  cmd = {
    '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    '-Dosgi.bundles.defaultStartLevel=4',
    '-Declipse.product=org.eclipse.jdt.ls.core.product',
    '-Dlog.protocol=true',
    '-Dlog.level=ALL',
    '-Xms2g',
    '-jar', '/usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
    '-configuration', '/usr/share/java/jdtls/config_linux',
    '-data', '/home/jummit/.cache/jdtls_vim/'..project_name,
  },
  root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'}),
}
```

### Eclipse.jdt.ls version

1.6.4

### Steps to Reproduce

Open a java file in a gradle project.

### Expected Result

After changing the code, the warnings/errors are updated. Autocompletion and tooltips work.

### Actual Result

Warnings and errors are only updated when opening the file, and after that the no LSP functions work anymore.

`:lua print(vim.inspect(vim.lsp.buf_get_clients()))` is empty.

This is the `lsp.log`:

```
[START][2022-03-05 09:31:05] LSP logging initiated
[WARN][2022-03-05 09:31:05] .../lua/vim/lsp.lua:1223    "buf_attach_client called on unloaded buffer (id: 1): "
[ERROR][2022-03-05 09:31:05] .../vim/lsp/rpc.lua:420    "rpc"   "java"  "stderr"        "WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"
[WARN][2022-03-05 09:31:07] ...lsp/handlers.lua:109     "The language server jdt.ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

When starting the server without arguments, this is the error in the log:
```bash
$java -jar /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar --verbose
An error has occurred. See the log file
/home/jummit/.eclipse/2139989682_linux_gtk_x86_64/configuration/1646469547229.log.
```

```
!SESSION 2022-03-05 09:39:07.161 -----------------------------------------------
eclipse.buildId=unknown
java.version=17.0.3
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  --verbose
Command-line arguments:  --verbose

!ENTRY org.eclipse.osgi 4 0 2022-03-05 09:39:07.359
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:81)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

Starting it with lspconfig's parameters works:
```bash
$/usr/lib/jvm/default/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.protocol=true -Dlog.level=ALL -Xms1g -Xmx2G --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -jar /usr/share/java/jdtls/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration /usr/share/java/jdtls/config_linux -data /home/jummit/.cache/jdtls_vim

WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign
Content-Length: 125

{"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Mar 5, 2022, 9:28:48 AM Main thread is waiting"}}
```

I'm using OpenJDK 17.0.3:
```bash
$java -version
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+3)
OpenJDK 64-Bit Server VM (build 17.0.3+3, mixed mode)
```

**Comment by mfussenegger** [comment]
>   "buf_attach_client called on unloaded buffer (id: 1): "


Sounds like you're calling `require"jdtls".start_or_attach` too early - it should be run as part of a java filetype event.

**Comment by Jummit** [comment]
> > "buf_attach_client called on unloaded buffer (id: 1): "
> 
> Sounds like you're calling `require"jdtls".start_or_attach` too early - it should be run as part of a java filetype event.

That was indeed the issue. Thanks so much for the help! I wonder if this should be documented somewhere though.

**Comment by mfussenegger** [comment]
> > > "buf_attach_client called on unloaded buffer (id: 1): "
> > 
> > 
> > Sounds like you're calling `require"jdtls".start_or_attach` too early - it should be run as part of a java filetype event.
> 
> That was indeed the issue. Thanks so much for the help! I wonder if this should be documented somewhere though.

It is in https://github.com/mfussenegger/nvim-jdtls#configuration

**Comment by Jummit** [comment]
Oh, I totally overread that it was in the ftplugins folder. My mistake.
