### ISSUE TITLE
Issue when opening Gradle project

### ISSUE THREAD

**Issue by josekoalas** [mfussenegger/nvim-jdtls#414]
### LSP client configuration

```lua
local project_name = vim.fn.fnamemodify(vim.fn.getcwd(), ':p:h:t')
project_name = project_name:gsub('%W', '_')
local workspace_folder = vim.fn.expand('$HOME/.cache/jdtls/data/') .. project_name

local config = {
    cmd = {
        'java',
        '-Declipse.application=org.eclipse.jdt.ls.core.id1',
        '-Dosgi.bundles.defaultStartLevel=4',
        '-Declipse.product=org.eclipse.jdt.ls.core.product',
        '-Dlog.protocol=true',
        '-Dlog.level=ALL',
        '-Xms1g',
        '--add-modules=ALL-SYSTEM',
        '--add-opens', 'java.base/java.util=ALL-UNNAMED',
        '--add-opens', 'java.base/java.lang=ALL-UNNAMED',
        '-jar', '/usr/local/Cellar/jdtls/1.19.0/libexec/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar',
        '-configuration', '/usr/local/Cellar/jdtls/1.19.0/libexec/config_mac',
        '-data', workspace_folder,
    },
    root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'}),
    settings = {
        java = {
            configuration = {
                runtimes = {
                    {
                        name = 'JavaSE-19',
                        path = '/usr/local/opt/openjdk/',
                    }
                }
            }
        }
    }
}
```

### Eclipse.jdt.ls version

1.19.0

### Steps to Reproduce

Gradle version: 7.6 (homebrew)
JDK version: Tried with both 19.0.2 and 17.0.6
Jdtls version: 1.19.0 (homebrew)
OS: MacOS 13.2

Steps to reproduce:

1. Create a java file in `src/main/java/something` (`Something.java`)
2. Add a simple hello world java code

```java
package hello;

public class Hello {
    public static void main(String[] args) {
        Greeter g = new Greeter();
        System.out.println("hey");
    }
}
```

3. Create `build.gradle` in the root directory of the project
4. Run `gradle` and `gradle build` (build is successful)
5. Open neovim and navigate to the java file
6. Jdtls starts loading and after a few moments the log bellow appears
7. No highlight or any lsp capabilities show up

NOTE: It does work when just using a .java file with nothing else in the directory (no gradle)

### Expected Result

The plugin working as intended

### Actual Result

<details>
  <summary>Error Log</summary>

[**Full log**](https://pastebin.com/iv3itKEf)

```
eclipse.buildId=unknown
java.version=19.0.2
java.vendor=Homebrew
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=es_ES
Command-line arguments:  -data /Users/jose/.cache/jdtls/data/0_Prueba

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.465
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.598
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.631
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.633
!MESSAGE Initializing Java Language Server 1.19.0.202301171536

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.658
!MESSAGE Static Commands: []

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.658
!MESSAGE Non-Static Commands: [java.edit.organizeImports, java.project.refreshDiagnostics, java.project.import, java.navigate.openTypeHierarchy, java.project.removeFromSourcePath, java.project.listSourcePaths, java.project.resolveStackTraceLocation, java.project.getAll, java.reloadBundles, java.project.isTestFile, java.edit.handlePasteEvent, java.project.getClasspaths, java.navigate.resolveTypeHierarchy, java.edit.stringFormatting, java.project.getSettings, java.project.updateSourceAttachment, java.project.resolveWorkspaceSymbol, java.project.upgradeGradle, java.project.createModuleInfo, java.protobuf.generateSources, java.project.resolveSourceAttachment, java.project.addToSourcePath, java.completion.onDidSelect]

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.663
!MESSAGE Starting org.eclipse.m2e.core

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:29.663
!MESSAGE Started org.eclipse.m2e.core 1ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:30.309
!MESSAGE ProjectRegistryRefreshJob finished 645ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:30.309
!MESSAGE Starting org.eclipse.buildship.core

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:30.365
!MESSAGE Started org.eclipse.buildship.core 56ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:30.376
!MESSAGE RepositoryRegistryUpdateJob finished 0ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:30.384
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:31.035
!MESSAGE Importing Gradle project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:31.036
!MESSAGE 0 Prueba was modified since last time the workspace was opened, must be synchronized

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-02-04 15:12:32.294
!MESSAGE Initialization failed 
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: assertion failed: Marker property value is too long: org.gradle.tooling.BuildActionFailureException: The supplied phased action failed with an exception.
	at org.gradle.tooling.internal.consumer.connection.PhasedActionAwareConsumerConnection.run(PhasedActionAwareConsumerConnection.java:58)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:62)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter$1.run(DefaultPhasedBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter$1.run(DefaultPhasedBuildActionExecuter.java:70)
	...
	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.startSynchronization(GradleProjectImporter.java:409)
	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importDir(GradleProjectImporter.java:297)
	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importToWorkspace(GradleProjectImporter.java:210)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:148)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:111)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:242)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.gradle.cache.CacheOpenException: Could not open init generic class cache for initialization script '/usr/local/Cellar/jdtls/1.19.0/libexec/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle' (/Users/jose/.gradle/caches/7.4.2/scripts/7s4n1zerenary6wu67e7f3xej).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:91)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:43)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:103)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:68)
	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.open(DefaultCacheRepository.java:117)
	...
	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.startSynchronization(GradleProjectImporter.java:409)
	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importDir(GradleProjectImporter.java:297)
	at org.eclipse.jdt.ls.core.internal.managers.GradleProjectImporter.importToWorkspace(GradleProjectImporter.java:210)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:148)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:111)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:242)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.335
!MESSAGE >> initialization job finished

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.337
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.436
!MESSAGE >> build jobs finished

!ENTRY org.eclipse.buildship.core 4 7 2023-02-04 15:12:32.440
!MESSAGE Synchronize Gradle projects with workspace failed due to an unexpected error.
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: assertion failed: Marker property value is too long: org.gradle.tooling.BuildActionFailureException: The supplied phased action failed with an exception.
	at org.gradle.tooling.internal.consumer.connection.PhasedActionAwareConsumerConnection.run(PhasedActionAwareConsumerConnection.java:58)
	at org.gradle.tooling.internal.consumer.connection.ParameterValidatingConsumerConnection.run(ParameterValidatingConsumerConnection.java:62)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter$1.run(DefaultPhasedBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.consumer.DefaultPhasedBuildActionExecuter$1.run(DefaultPhasedBuildActionExecuter.java:70)
	at org.gradle.tooling.internal.consumer.connection.LazyConsumerActionExecutor.run(LazyConsumerActionExecutor.java:143)
	...
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager$WorkspaceRunnableAdapter.run(DefaultToolingApiOperationManager.java:58)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2380)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:39)
	at org.eclipse.buildship.core.internal.operation.ToolingApiJob.run(ToolingApiJob.java:65)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.gradle.cache.CacheOpenException: Could not open init generic class cache for initialization script '/usr/local/Cellar/jdtls/1.19.0/libexec/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle' (/Users/jose/.gradle/caches/7.4.2/scripts/7s4n1zerenary6wu67e7f3xej).
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:91)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:43)
	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:103)
	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:68)
	...
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2405)
	at org.eclipse.buildship.core.internal.operation.DefaultToolingApiOperationManager.run(DefaultToolingApiOperationManager.java:39)
	at org.eclipse.buildship.core.internal.operation.ToolingApiJob.run(ToolingApiJob.java:65)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.452
!MESSAGE >> registerWatchers'

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.453
!MESSAGE >> watchers registered

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.586
!MESSAGE JVM Runtimes changed, saving new configuration

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.593
!MESSAGE >> java/buildWorkspace (full)

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.595
!MESSAGE >> New configuration: {java={configuration={runtimes=[{name=JavaSE-19, path=/usr/local/opt/openjdk/}]}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.596
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.813
!MESSAGE >> New configuration: {java={configuration={runtimes=[{name=JavaSE-19, path=/usr/local/opt/openjdk/}]}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2023-02-04 15:12:32.815
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 4 0 2023-02-04 15:12:32.815
!MESSAGE Error occured while building workspace. Details: 
 message: The supplied phased action failed with an exception.
Could not open init generic class cache for initialization script '/usr/local/Cellar/jdtls/1.19.0/libexec/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle' (/Users/jose/.gradle/caches/7.4.2/scripts/7s4n1zerenary6wu67e7f3xej).
Could not compile initialization script '/usr/local/Cellar/jdtls/1.19.0/libexec/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle'.
startup failed:
General error during conversion: Unsupported class file major version 63
java.lang.IllegalArgumentException: Unsupported class file major version 63
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
	...
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
1 error; code: 0; resource: /Users/jose/Library/Mobile Documents/com~apple~CloudDocs/Estudios/10 Informatica Primero/Diseño de Software/Practicas/0 Prueba;
 message: The supplied phased action failed with an exception.
Could not open init generic class cache for initialization script '/usr/local/Cellar/jdtls/1.19.0/libexec/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle' (/Users/jose/.gradle/caches/7.4.2/scripts/7s4n1zerenary6wu67e7f3xej).
Could not compile initialization script '/usr/local/Cellar/jdtls/1.19.0/libexec/config_mac/org.eclipse.osgi/50/0/.cp/gradle/init/init.gradle'.
startup failed:
General error during conversion: Unsupported class file major version 63
java.lang.IllegalArgumentException: Unsupported class file major version 63
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:199)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:180)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:166)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:287)
	at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:81)
	at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:251)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:189)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	...
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
1 error; code: 0; resource: /Users/jose/Library/Mobile Documents/com~apple~CloudDocs/Estudios/10 Informatica Primero/Diseño de Software/Practicas/0 Prueba;
```

<details>

**Comment by josekoalas** [comment]
Nevermind, when reinstalling everything from scratch the error went away, it works great now! Thank you for this wonderful plugin.

**Comment by LordMZTE** [comment]
I'm getting this and didn't manage to fix it.

**Comment by W1nter-isHere** [comment]
Getting this error as well and reinstalling did not fix it. On Arch Linux tried installing jdtls from Mason and AUR.

**Comment by W1nter-isHere** [comment]
It seems to work for a brand new gradle project but does not in my existing ones.

**Comment by mfussenegger** [comment]
Please follow the [troubleshooting](https://github.com/mfussenegger/nvim-jdtls#troubleshooting) steps. If you still can't get it working, and you believe it's a client bug open a new issue with _minimal_ _reproduction_ steps. The one line comments here are just noice where I can't act on.
