### ISSUE TITLE
Jdtls complains about java not meeting the minimum version requirement

### ISSUE THREAD

**Issue by nucatus** [mfussenegger/nvim-jdtls#420]
### LSP client configuration

```
local java17_home = '/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/'
local jdtls_home = vim.fn.stdpath('data') .. '/mason/packages/jdtls'
local jdtls_conf = jdtls_home .. '/config_mac'
local jdtls_plugin = jdtls_home .. '/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar'

local root_markers = {'.git', 'gradlew', 'mvnw', 'build.gradle'}
local root_dir = require('jdtls.setup').find_root(root_markers)
local workspace_dir = vim.fn.stdpath('data') .. '/eclipse-data/prejects/' .. vim.fn.fnamemodify(root_dir, ':p:h:t')

-- See `:help vim.lsp.start_client` for an overview of the supported `config` options.
local config = {
  -- The command that starts the language server
  -- See: https://github.com/eclipse/eclipse.jdt.ls#running-from-the-command-line
  cmd = {

    -- 💀
    -- 'java', -- or '/path/to/java17_or_newer/bin/java'
            -- depends on if `java` is in your $PATH env variable and if it points to the right version.
    java17_home .. '/bin/java',
    '-Declipse.application=org.eclipse.jdt.ls.core.id1',
    '-Dosgi.bundles.defaultStartLevel=4',
    '-Declipse.product=org.eclipse.jdt.ls.core.product',
    '-Dlog.protocol=true',
    '-Dlog.level=ALL',
    '-Xms1g',
    '--add-modules=ALL-SYSTEM',
    '--add-opens', 'java.base/java.util=ALL-UNNAMED',
    '--add-opens', 'java.base/java.lang=ALL-UNNAMED',

    -- 💀
    -- '-jar', '/path/to/jdtls_install_location/plugins/org.eclipse.equinox.launcher_VERSION_NUMBER.jar',
         -- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                       ^^^^^^^^^^^^^^
         -- Must point to the                                                     Change this to
         -- eclipse.jdt.ls installation                                           the actual version
    '-jar', jdtls_plugin,

    -- 💀
    -- '-configuration', '/path/to/jdtls_install_location/config_SYSTEM',
                    -- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        ^^^^^^
                    -- Must point to the                      Change to one of `linux`, `win` or `mac`
                    -- eclipse.jdt.ls installation            Depending on your system.
    '-configuration', jdtls_conf,

    -- 💀
    -- See `data directory configuration` section in the README
    -- '-data', '/path/to/unique/per/project/workspace/folder'
    '-data', workspace_dir
  },

  -- 💀
  -- This is the default if not provided, you can remove it. Or adjust as needed.
  -- One dedicated LSP server & client will be started per unique root_dir
  -- root_dir = require('jdtls.setup').find_root({'.git', 'mvnw', 'gradlew'}),
  root_dir = root_dir,

  -- Here you can configure eclipse.jdt.ls specific settings
  -- See https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request
  -- for a list of options
  settings = {
    java = {
    }
  },

  -- Language server `initializationOptions`
  -- You need to extend the `bundles` with paths to jar files
  -- if you want to use additional eclipse.jdt.ls plugins.
  --
  -- See https://github.com/mfussenegger/nvim-jdtls#java-debug-installation
  --
  -- If you don't plan on using the debugger or other eclipse.jdt.ls plugins you can remove this
  init_options = {
    bundles = {}
  },
}
-- This starts a new client & server,
-- or attaches to an existing client & server depending on the `root_dir`.
require('jdtls').start_or_attach(config)
```

### Eclipse.jdt.ls version

1.19.0.202301171536

### Steps to Reproduce

I created a default jdtls configuration with a clean install and the basic configuration provided in the plugin documentation. 
However, jdtls complains thet the Java version doesn't meet the minimum criteria. Even if I change to the latest java GA version 19, I get the same result.

### Expected Result

The LSP client starts with no errors.

### Actual Result

LSP client crashes with the message
`Client 2 quit with exit code 1 and signal 0`

and the LSP logs say that the Java version requirement is not met.
```
[START][2023-02-11 06:25:54] LSP logging initiated
[ERROR][2023-02-11 06:25:54] .../vim/lsp/rpc.lua:733	"rpc"	"/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home//bin/java"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector\n"
[WARN][2023-02-11 06:26:06] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/inlayHint/refresh"
[WARN][2023-02-11 06:26:07] ...lsp/handlers.lua:113	"The language server jdtls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2023-02-11 06:26:07] ...lsp/handlers.lua:485	"11 Feb 2023, 06:26:07 Command _java.reloadBundles.command not supported on client"
[START][2023-02-11 06:26:47] LSP logging initiated
[ERROR][2023-02-11 06:26:47] .../vim/lsp/rpc.lua:733	"rpc"	"/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home//bin/java"	"stderr"	"WARNING: Using incubator modules: jdk.incubator.vector, jdk.incubator.foreign\n"
[ERROR][2023-02-11 06:26:48] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	'Traceback (most recent call last):\n  File "/Users/nucatus/.local/share/nvim/mason/bin/jdtls", line 17, in <module>\n'
[ERROR][2023-02-11 06:26:48] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	'    jdtls.main(sys.argv[1:])\n  File "/Users/nucatus/.local/share/nvim/mason/packages/jdtls/bin/jdtls.py", line 81, in main\n'
[ERROR][2023-02-11 06:26:48] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	'    java_executable = get_java_executable(known_args.validate_java_version)\n  File "/Users/nucatus/.local/share/nvim/mason/packages/jdtls/bin/jdtls.py", line 40, in get_java_executable\n'
[ERROR][2023-02-11 06:26:48] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	'    raise Exception("jdtls requires at least Java 17")\n'
[ERROR][2023-02-11 06:26:48] .../vim/lsp/rpc.lua:733	"rpc"	"jdtls"	"stderr"	"Exception: jdtls requires at least Java 17\n"
```

**Comment by mfussenegger** [comment]
It looks like the error is coming from `.local/share/nvim/mason/bin/jdtls` / `.local/share/nvim/mason/packages/jdtls/bin/jdtls.py` and not from the configuration you posted. Looks like you have a second jdtls setup somewhere.

`jdtls.py` probably contains a broken Java version detection.

**Comment by nucatus** [comment]
@mfussenegger thanks for looking into it.
Could this be because `jdtls` is installed via mason as an LSP and also via `mfussenegger/nvim-jdtls`? Are these ways of installing jdtls mutually exclussive?
How can I check where these installations of jdtls are coming from?

**Comment by mfussenegger** [comment]
You should be able to install eclipse.jdt.ls via mason, but the LSP configuration shouldn't be duplicated.

Are you also using mason-lspconfig or some other lsp configuration magic plugin? Could be that they are trying to launch eclipse.jdt.ls as well.

Can you also show the output of `/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java -version` ?
That would allow fixing the logic here:

https://github.com/eclipse/eclipse.jdt.ls/blob/fecf51c318e766dc81acc414a1544ccd79ef4604/org.eclipse.jdt.ls.product/scripts/jdtls.py#L35-L44

**Comment by nucatus** [comment]
Yes, `mason-lspconfig` was present in the list of plugins via the `VonHeikemen/lsp-zero.nvim` LSP configurator plugin. I haven't tested yet what happens if I remove the plugin, since doing so breakes my whole LSP configuration. 

```
    use {
	    'VonHeikemen/lsp-zero.nvim',
	    branch = 'v1.x',
	    requires = {
    		  -- LSP Support
    		  {'neovim/nvim-lspconfig'},
    		  {'williamboman/mason.nvim'},
    		  -- {'williamboman/mason-lspconfig.nvim'},

		      -- Autocompletion
		      {'hrsh7th/nvim-cmp'},
	    	  {'hrsh7th/cmp-buffer'},
	    	  {'hrsh7th/cmp-path'},
    		  {'saadparwaiz1/cmp_luasnip'},
    		  {'hrsh7th/cmp-nvim-lsp'},
    		  {'hrsh7th/cmp-nvim-lua'},

		      -- Snippets
	    	  {'L3MON4D3/LuaSnip'},
		      {'rafamadriz/friendly-snippets'},
	    }
    }
    use 'mfussenegger/nvim-dap'
    use 'mfussenegger/nvim-jdtls'
```

Would it be possible to deactivate that jdtls configuration while still keeping the `mason-lspconfig` in the list of the `lsp-zero` requiered plugins?

This is the output of the `java -version` command:
```
➜  ~ /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
```

**Comment by mfussenegger** [comment]
From what I can tell the jdtls.py version can handle that version output. Maybe your `JAVA_HOME` is pointing to a different java, or it's picking up an older outdated eclipse.jdt.ls.

In any case you don't want to run two clients with two eclipse.jdt.ls processes.

You'll have to check lsp-zero.nvim/mason-lspconfig to see how you can prevent it from setting up jdtls as well
