### ISSUE TITLE
FileNotFound when initializing workspaces

### ISSUE THREAD

**Issue by minhduc0711** [mfussenegger/nvim-jdtls#95]
I'm working on multiple Java projects, but I am not able to get jdtls to initialize the workspace properly. As a result, the LSP prints lots of import errors.
Here's the relevant part in the log file
```
!ENTRY org.eclipse.jdt.ls.core 4 0 2021-06-11 10:21:21.957
!MESSAGE Could not write workspace metadata '/home/minhduc0711/.local/share/eclipse/gama/.metadata/.plugins/org.eclipse.core.resources/.root/3.tree'.
!STACK 1
org.eclipse.core.internal.resources.ResourceException(/)[568]: java.io.FileNotFoundException: /home/minhduc0711/.local/share/eclipse/gama/.metadata/.plugins/org.eclipse.core.resources/.root/3.tree (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at org.eclipse.core.internal.localstore.SafeFileOutputStream.<init>(SafeFileOutputStream.java:55)
	at org.eclipse.core.internal.resources.SaveManager.saveTree(SaveManager.java:1381)
	at org.eclipse.core.internal.resources.SaveManager.save(SaveManager.java:1168)
	at org.eclipse.core.internal.resources.Workspace.save(Workspace.java:2354)
	at org.eclipse.core.internal.resources.Workspace.save(Workspace.java:2343)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer$1.run(JDTLanguageServer.java:180)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I believe my `root_dir` is set correctly because I saw startup messages indicating the correct projects were imported.
My temporary workaround is to create a workspace and import projects using Eclipse IDE, and then use that workspace for jdtls.

**Comment by mfussenegger** [comment]
Are you ensuring that you use a separate workspace directory per project?

**Comment by minhduc0711** [comment]
Yes, I'm trying to create a brand new workspace. Are jdtls supposed to work with a multi-project setup similar to [this](https://github.com/gama-platform/gama)?

**Comment by mfussenegger** [comment]
There are a couple of issues in eclipse.jdt.ls about that:

- https://github.com/eclipse/eclipse.jdt.ls/issues/311
- https://github.com/eclipse/eclipse.jdt.ls/issues/503
- https://github.com/eclipse/eclipse.jdt.ls/issues/1303


I know that jdtls handles gradle projects with multiple modules well, but I never tried multi-project maven setups.
It may be possible to open one project as `root_dir` and then add the others using `vim.buf.lsp.add_workspace_folder` - but I didn't try it myself.

**Comment by blmhemu** [comment]
Hi @minhduc0711 ! Were you able to get it working? I guess I am in the same boat as yours.

**Comment by minhduc0711** [comment]
@blmhemu No sadly, I still have to use the workaround mentioned above:
> create a workspace and import projects using Eclipse IDE, and then use that workspace for jdtls.

**Comment by mfussenegger** [comment]
Closing this here since it is an upstream issue
